crs/campus/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views
# from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('student/student_register/' , views.student_register , name='student_register'),
    path('student/student_login/', views.student_login,name='student_login'),
    path('student/student_login/usd/',views.usd,name='usd'),
    path('logout/', views.pagelogout, name='logout'),
    path('student/student_login/dispstu/',views.dispstu,name='dispstu'),
    path('company/company_register/', views.company_register, name='company_register'),
    path('company/company_login/', views.company_login, name='company_login'),
    path('company/company_login/ccd/', views.ccd, name='ccd'),
    path('company/company_login/jp/', views.jobpos, name='jp'),
    path('company/company_login/jd/', views.jd, name='jd'),
    path('company/company_login/deletevacan/', views.deletevacan, name='deletevacn'),
    path('company/company_login/viewpos/', views.viewpos, name='viewpos'),
    path('student/student_login/applyjob/', views.applyjob, name='apply'),
    path('student/student_login/applyjob/<str:opt>/', views.apply, name='apply1'),
    path('', views.home, name='home'),
    path('company/company_login/selectstu/', views.selectstu, name='sstu'),
    path('company/company_login/selectstu/<str:opt>/',views.stumail,name="sm")
    

]

crs/crs/urls.py
from django.contrib import admin
from django.urls import path ,include
# from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('campus.urls')),
    path('student/student_register/', include('campus.urls')),
    path('student/student_login/',include('campus.urls')),
    path('student/student_login/usd/',include('campus.urls')),
    path('logout/',include('campus.urls')),
    path('student/student_login/dispstu/', include('campus.urls')),
    path('company/company_register/', include('campus.urls')),
    path('company/company_login/', include('campus.urls')),
    path('company/company_login/ccd/',include('campus.urls')),
    path('company/company_login/jp/', include('campus.urls')),
    path('company/company_login/jd/', include('campus.urls')),
    path('company/company_login/viewpos/', include('campus.urls')),
    path('student/student_login/applyjob/',include('campus.urls')),
    path('student/student_login/applyjob/<str:opt>/',include('campus.urls')),
    path('company/company_login/selectstu/', include('campus.urls')),
    path('company/company_login/selectstu/<str:opt>/',include('campus.urls')),

]

crs/campus/models.py
from django.core.validators import MaxValueValidator,MinValueValidator,MaxLengthValidator,MinLengthValidator
from django.db import models
from django.contrib.auth.models import  AbstractUser
from django.contrib.auth.models import User

done = (
    ('yes', 'yes'),
    ('no', 'no'),
)


class stu_details(models.Model):
    branch_choices = (
        ('it', 'information_technology'),
        ('me', 'mech'),
        ('ce', 'civil'),
        ('eee', 'eee'),
        ('ece', 'ece'),
        ('ch', 'chemical'),
        ('cse', 'cse'),
    )
    gender = (
        ('male', 'male'),
        ('female', 'female'),
        ('others','others'))

    username=models.CharField(max_length=9,blank=False,help_text="enter username ex:y16it***",default="y1")
    name = models.CharField(max_length=30, blank=False, help_text='*required',default="full name")
    phone_number = models.CharField(validators=[MaxLengthValidator(10),MinLengthValidator(10)] ,help_text='*required',max_length=10)
    fathers_name = models.CharField(max_length=30, blank=False, help_text='*required')
    mothers_name = models.CharField(max_length=30, blank=False, help_text='*required')
    gender=models.CharField(blank=False, choices=gender,max_length=10)
    place = models.CharField(max_length=30, blank=False)
    branch = models.CharField(blank=False, choices=branch_choices, max_length=10)
    cgpa_Btech = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(10)],blank=False,help_text='*required')
    class_10_cgpa = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(10)],blank=False,help_text='*required')
    class_12_percentage = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(100)],blank=False,help_text='*required')
    certifications_count = models.IntegerField(blank=False)
    internship = models.CharField(blank=False, choices=done,max_length=10)
    languages = models.CharField(max_length=100, blank=False, help_text='*required')
    sop = models.CharField(max_length=500, default="statement of purpose", help_text='*required')
    dob = models.DateField(blank=False, help_text='*format is YYYY-MM-DD', )
    email = models.EmailField(max_length=254, blank=False, help_text='Required. Inform a valid email address.',default="anudeep.insvirat@gmail.com")

    def __str__(self):
       return self.username


class comp_details(models.Model):
    username=models.CharField(max_length=30,blank=False , help_text='*required')
    company_name = models.CharField(max_length=30, blank=False, help_text='*required')
    est_year = models.CharField(max_length=4, blank=False, help_text="*required")
    hr_name = models.CharField(max_length=30, blank=False, help_text='*required')
    hr_phn = models.CharField(max_length=10,validators=[MinValueValidator(10),MaxValueValidator(10)], blank=False, help_text='*required')
    headquaters = models.CharField(max_length=30,blank=False, help_text='*required')
    about = models.CharField(max_length=1000, blank=False, help_text='*required')
    type = models.CharField(max_length=100, blank=False)
    email = models.EmailField(max_length=254,blank=False, help_text='Required. Inform a valid email address.')

    def __str__(self):
        return self.username

class job_pos(models.Model):
    job_id=models.BigAutoField(primary_key=True)
    username = models.CharField(max_length=30, blank=False, help_text='*required')
    company_name = models.CharField(max_length=30, blank=False, help_text='*required')
    designation = models.CharField(max_length=30, blank=False, help_text='*required')
    salary=models.IntegerField( blank=False, help_text='*required')
    bond_years=models.IntegerField( blank=False, help_text='*required')
    information_technology= models.CharField(blank=False, choices=done, max_length=10)
    mech= models.CharField(blank=False, choices=done, max_length=10)
    civil= models.CharField(blank=False, choices=done, max_length=10)
    eee = models.CharField(blank=False, choices=done, max_length=10)
    ece= models.CharField(blank=False, choices=done, max_length=10)
    chemical= models.CharField(blank=False, choices=done, max_length=10)
    cse= models.CharField(blank=False, choices=done, max_length=10)

    def __str__(self):
        return str(self.job_id)


class applied_jobs(models.Model):
    company_id = models.CharField(max_length=30, blank=False, help_text='*required' ,default="company id")
    job_id = models.CharField(max_length=30, blank=False, help_text='*required',default="job id")
    student_id= models.CharField(max_length=9, blank=False, help_text="enter username ex:y16it***", default="y1")

    def __str__(self):
        return self.job_id

crs/campus/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import Student_SignUpForm,UsdForm,dispstuForm,company_SignUpForm,ccdForm,jobposForm
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from campus.models import stu_details,comp_details,job_pos,applied_jobs
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator

# Create your views here
def  student_login(request):
    if request.user.is_authenticated and request.user.groups.filter(name='student').exists():
        return render(request,'campus/stulog.html')
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if request.user.groups.filter(name='student').exists():
             return render(request, 'campus/stulog.html', {'form': form})
            else:
                logout(request)
                return render(request, 'campus/student_login.html', {'form': form})
        else:
            return render(request, 'campus/student_login.html', {'form': form})


    else:
        form = AuthenticationForm()
        return render(request, 'campus/student_login.html', {'form': form})

def  home(request):
    return render(request,'campus/home.html')

def pagelogout(request):
        logout(request)

        return redirect('http://127.0.0.1:8000/')


def student_register(request):
    if request.method == 'POST':
        form = Student_SignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
            group = Group.objects.get(name='student')
            user.groups.add(group)
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('http://127.0.0.1:8000/student/student_login/')

        else:
            return render(request, 'campus/register.html', {'form': form})
    else:
        form =Student_SignUpForm()
        return render(request, 'campus/register.html', {'form': form})

#@login_required
#@user_passes_test(lambda u: u.groups.filter(name='Student').count() == 1)
def usd(request):
 if  request.user.is_authenticated and request.user.groups.filter(name='student').exists():
    if request.method == "POST":
            form=UsdForm(request.POST)
            if form.is_valid():
                stu = request.user.username
                post = stu_details.objects.filter(username=stu)
                x= request.POST.get('sop')
                y=request.POST.get('phone_number')
                db=request.POST.get('dob')
                e=request.POST.get('email')
                l=request.POST.get('languages') 
                cc=request.POST.get('certifications_count')
                i=request.POST.get('internship')
                c12=request.POST.get('class_12_percentage')
                c10=request.POST.get('class_10_cgpa')
                b=request.POST.get('branch')
                cb=request.POST.get('cgpa_Btech')
                p=request.POST.get('place')
                g=request.POST.get('gender')
                fn=request.POST.get('fathers_name')
                mn=request.POST.get('mothers_name')
                name=request.POST.get('name')
                print(fn)
                if(len(post)>0):
                  j=post[0]
                else:
                    j=stu_details()
                j.sop =x
                j.phone_number = y
                j.dob=db
                j.email=e
                j.languages=l
                j.certifications_count=cc
                j.internship=i
                j.class_12_percentage=c12
                j.class_10_cgpa=c10
                j.branch=b
                j.cgpa_Btech=cb
                j.place=p
                j.gender=g
                j.fathers_name=fn
                j.mothers_name=mn
                j.name=name
                j.username=stu
                j.save()
                return render(request, 'campus/stulog.html')

    else:
        stu = request.user.username
        post = stu_details.objects.filter(username=stu)
        if(len(post)>0):
            x = post[0].sop
            x=str(x)
            y = post[0].phone_number
            print(x,y,post)
            form=UsdForm()
            db=post[0].dob
            e=post[0].email
            l=post[0].languages 
            cc=post[0].certifications_count
            i=post[0].internship
            c12=post[0].class_12_percentage
            c10=post[0].class_10_cgpa
            b=post[0].branch
            cb=post[0].cgpa_Btech
            p=post[0].place
            g=post[0].gender
            fn=post[0].fathers_name
            mn=post[0].mothers_name
            name=post[0].name
            context={'form': form,'x':x,'y':y,'db': db,"e":e,"l":l,"cc":cc,"i":i,"c12":c12,"c10":c10,"b":b,"cb":cb,"p":p,"g":g,"fn":fn,"mn":mn,"name":name}
            return render(request, 'campus/usd.html',context)
        else:
            form=UsdForm()
            context={'form': form}
            return render(request, 'campus/usd.html',context)

 else:
     return HttpResponse('<h1>You are not logged in. <a href="http://127.0.0.1:8000/  " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem; color: #4BB543">Back</b></a></h1>')



def dispstu(request):
    if request.user.is_authenticated and request.user.groups.filter(name='student').exists():
        stu = request.user.username
        print(stu)
        posts = stu_details.objects.filter(username=stu)
        print(posts)
        form=dispstuForm()
        return render(request, 'campus/dispstu.html', {'form': form, 'posts': posts})
    else:
        return HttpResponse('<h1>You are not logged in. <a href="http://127.0.0.1:8000/  " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem; color: #4BB543">Back</b></a></h1>')



def company_register(request):
    if request.method == 'POST':
        form = company_SignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
            group = Group.objects.get(name='company')
            user.groups.add(group)
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            a=comp_details()
            a.username=request.POST.get('username')
            a.company_name=request.POST.get('company_name')
            a.email=request.POST.get('email')
            a.est_year=request.POST.get('est_year')
            a.type=request.POST.get('type')
            a.about=request.POST.get('about')
            a.hr_name=request.POST.get('hr_name')
            a.hr_phn=request.POST.get('hr_phn')
            a.headquaters=request.POST.get('headquaters')
            a.save()
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('http://127.0.0.1:8000/')
        else:
            return render(request, 'campus/register1.html', {'form': form})

    else:
        form =company_SignUpForm()
        return render(request, 'campus/register1.html', {'form': form})



def  company_login(request):
    if request.user.is_authenticated and request.user.groups.filter(name='company').exists():
        return render(request,'campus/comlog.html')
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if request.user.groups.filter(name='company').exists():
             return render(request, 'campus/comlog.html', {'form': form})
            else:
                logout(request)
                return render(request, 'campus/company_login.html', {'form': form})
        else:
            return render(request, 'campus/company_login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'campus/company_login.html', {'form': form})




def ccd(request):
 if  request.user.is_authenticated and request.user.groups.filter(name='company').exists():
    if request.method == "POST":
            form=ccdForm(request.POST)
            if form.is_valid():
                stu = request.user.username
                post = comp_details.objects.filter(username=stu)
                x= request.POST.get('hr_name')
                y=request.POST.get('hr_phn')
                z=request.POST.get('about')
                j=post[0]
                j.hr_name =x
                j.hr_phn = y
                j.about=z
                j.save()
                return render(request, 'campus/comlog.html')

    else:
        stu = request.user.username
        post = comp_details.objects.filter(username=stu)
        x = post[0].hr_name
        x=str(x)
        y = post[0].hr_phn
        z=post[0].about
        form=ccdForm()
        return render(request, 'campus/ccd.html', {'form': form,'x':x,'y':y,'z':z})
 else:
     return HttpResponse('<h1>You are not logged in. <a href="http://127.0.0.1:8000/  " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem; color: #4BB543">Back</b></a></h1>')



def jobpos(request):
    if request.user.is_authenticated and request.user.groups.filter(name='company').exists():
        if request.method == "POST":
            form = jobposForm(request.POST)

crs/campus/templates/campus/comlog.html
<!DOCTYPE html>
{%extends "campus/base.html"%}

{%block body_block%}
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto text-center mb-5 section-heading">
         
          <br>
          <h2>DASHBOARD</h2>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="container">
        <div class="jumbotron">
            <table class="pos2 d-flex justify-content-center">
                <tr>
                    <td><a href=" http://127.0.0.1:8000/company/company_login/jp/  " class="btn btn-lg btn-primary mx-5 d-inline-flex "><b style="font-size: 2rem">Post vacancy</b></a></td></tr> <!-- <tr>
                <td><a href="http://127.0.0.1:8000/company/company_login/jd/  " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem">Update vacancy</b></a></td></tr> -->
              <tr>
                <td><a href=" http://127.0.0.1:8000/company/company_login/selectstu/ " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem">Select students</b></a></td>
              </tr>
              <tr>  <td ><a href=" http://127.0.0.1:8000/company/company_login/ccd/ " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem">Update Company details</b></a></td>
            
                </tr>
                <!-- <tr>  <td ><a href=" http://127.0.0.1:8000/company/company_login/deletevacan/ " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem">Delete vacancy</b></a></td>
            
                </tr>  -->
                <tr>  <td ><a href=" http://127.0.0.1:8000/company/company_login/viewpos/ " class="btn btn-lg btn-primary mx-5 d-inline-flex"><b style="font-size: 2rem">Posted vacancies</b></a></td>
            
                </tr>
            </table>
        </div>
          
      </div>
    </div>
    
    
{%endblock%}

crs/campus/templates/campus/company_login.html
{%extends "campus/base.html"%}

{%block body_block%}
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto text-center mb-5 section-heading">
         
          <br>
          <h2>COMPANY LOGIN</h2>
        </div>
      </div>
    </div>
  <div  class="container">
    <div class="jumbotron ">
        <table class="hi">
            <tr>
        
             <form method="post">
        {% csrf_token %}
        {{form.as_table}}
        
        
            <tr>  <td><p><button type="submit"  class="btn btn-lg btn-primary  d-inline-flex "">Login</button></p></td></tr>
        </form>
                </tr>
                <tr>
                <td><center>
        <a href="company/company_register/" class=" d-inline-flex "  style="color:deepskyblue"><b>New user? Register here</b></a>
                </center></td>
        </tr>
        </table>
    </div>
  </div>
    
{%endblock%}

crs/campus/templates/campus/jobpos.html
<!DOCTYPE html>
{%extends "campus/base.html"%}

{%block body_block%}
          <div class="row">
              <div class="col-md-6 mx-auto text-center mb-5 section-heading">
               
                <br>
                <h2>Post Vacancy</h2>
              </div>
            </div>
          <div class="container">
          <div class="jumbotron">
              <form method="post" >


                  {% if messages %}
                     <ul>
                         {% for message in messages %}
                         <li>{{ message }}</li>
                         {% endfor %}
                     </ul>
                 {% endif %}
         
         
                {% if form.errors %}
             {% for field in form %}
                 {% for error in field.errors %}
                     <div class="alert alert-danger">
                         <strong>{{ error|escape }}</strong>
                     </div>
                 {% endfor %}
             {% endfor %}
             {% for error in form.non_field_errors %}
                 <div class="alert alert-danger">
                     <strong>{{ error|escape }}</strong>
                 </div>
             {% endfor %}
         {% endif %}
         
         
         
             {% csrf_token %}
             <table>
             <tr><th></th><td><input type="hidden" name="company_name"  size="36" maxlength="30" required id="id_company_name" value={{ y }}  ></td></tr>
         <tr><th></th><td><input type="hidden" name="username" maxlength="30" required id="id_username" value={{ x }} > </td></tr><br>
         <!-- <tr><th><label for="id_job_id">Job id:</label></th><td><input type="text" name="job_id" maxlength="30" required id="id_job_id"><span class="helptext"></span></td></tr><br> -->
         <tr><th><label for="id_designation">Designation:</label></th><td><input type="text" name="designation" maxlength="30" required id="id_designation"><span class="helptext"></span></td></tr><br>
         <tr><th><label for="id_salary">Salary:</label></th><td><input type="number" name="salary" required id="id_salary"><span class="helptext"></span></td></tr><br>
         <tr><th><label for="id_bond_years">Bond years:</label></th><td><input type="number" name="bond_years" required id="id_bond_years"><span class="helptext"></span></td></tr><br>
         <tr><th><label for="id_information_technology">Information Technology:</label></th><td><select name="information_technology" required id="id_information_technology">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_cse">Computer Engineering:</label></th><td><select name="cse" required id="id_cse">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_mech">Mech:</label></th><td><select name="mech" required id="id_mech">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_civil">Civil:</label></th><td><select name="civil" required id="id_civil">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_eee">Electrical:</label></th><td><select name="eee" required id="id_eee">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_ece">Electronics:</label></th><td><select name="ece" required id="id_ece">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_chemical">Chemical:</label></th><td><select name="chemical" required id="id_chemical">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         
         
             <br></table>
         <button type="submit" class="btn btn-primary"style="font-size: 1rem;">Submit</button>
         </form>
          </div>
          


      </div>
      


{%endblock%}
 

crs/campus/templates/campus/usd.html
         <!DOCTYPE html>
         {%extends "campus/base.html"%}
         
         {%block body_block%}
             <div class="container-fluid">
               
                   <div class="row">
                       <div class="col-md-6 mx-auto text-center mb-5 section-heading">
                        
                         <br>
                         <h2>Modify Details</h2>
                       </div>
                     </div>
                   </div>
                   <div class="container">
                   <div class="jumbotron">
                      

                      {% if form.errors %}
                      {% for field in form %}
                          {% for error in field.errors %}
                              <div class="alert alert-danger">
                                  <strong>{{ error|escape }}</strong>
                              </div>
                          {% endfor %}
                      {% endfor %}
                      {% for error in form.non_field_errors %}
                          <div class="alert alert-danger">
                              <strong>{{ error|escape }}</strong>
                          </div>
                      {% endfor %}
                  {% endif %}
                  
                  
                           <form method="post" >
                              {% csrf_token %}
                               <table>
                                    <tr><th><label for="id_phone_number">Phone number:</label></th><td><input type="text" name="phone_number" maxlength="10" minlength="10" required id="id_phone_number"  value="{{ y }}"></td></tr>
                                    <tr><th><label>DOB</label></th><td><input type="date"  value="{{ db }}" name="dob" min="1995-01-01" max="2006-01-01" required></td></tr>
                                    <tr><th><label>Name</label></th><td><input type="text"  value="{{ name }}" name="name"></td></tr>
                                    <tr><th><label>Father's name</label></th><td><input type="text"  value="{{ fn }}" name="fathers_name"></td></tr>
                                    <tr><th><label>Mother's Name</label></th><td><input type="text"  value="{{ mn }}" name="mothers_name"></td></tr>
                                    <tr><th><label>Branch</label></th><td>
                                        <select name="branch" required id="id_branch">
                                          <option value="">---------</option>

                                          <option value="it">information technology</option>

                                          <option value="cse">computer engineering</option>

                                          <option value="me">mech</option>

                                          <option value="ce">civil</option>

                                          <option value="eee">eee</option>

                                          <option value="ece">ece</option>

                                          <option value="ch">chemical</option>


                                        </select>
                                                                            </td></tr>
                                    <tr><th><label>Gender</label></th>
                                        <td>
                                        <input type="radio" name="gender" value="female" >female
                                        <input type="radio" name="gender" value="male" >male
                                        <input type="radio" name="gender" value="others" >others
                                        </td>
                                    </tr>
                                    <tr><th><label>Place</label></th><td><input type="text"  value="{{ p }}" name="place"></td></tr>
                                    <tr><th><label>Class 10 Percentage</label></th><td><input type="number" value="{{ c10 }}" name="class_10_cgpa" max="100"></td></tr>
                                    <tr><th><label>Class 12 Percentage</label></th><td><input type="number" value="{{ c12 }}" name="class_12_percentage" max="100"></td></tr>
                                    <tr><th><label>Btech CGPA</label></th><td><input type="number" value="{{ cb }}" name="cgpa_Btech" max="10"></td></tr>
                                    <!-- <input type="text" value="yes/no" value="{{ i }}" name="internship"> -->
                                    <tr><th><label>Internship</label></th><td>
                                        <select name="internship" required>
                                          <option value="">---------</option>

                                          <option value="yes">Yes</option>

                                          <option value="no">No</option>

                                        </select>
                                    </td></tr>
                                    <tr><th><label>Certification count</label></th><td><input type="number"  value="{{ cc }}" name="certifications_count"></td></tr>
                                    <tr><th><label>languages</label></th><td><input type="text"  value="{{ l }}" name="languages"></td></tr>
                                    <tr><th><label>Email</label></th><td><input type="email" value="{{ e }}" name="email"></td></tr>
                                    <tr><th><label for="id_sop" value="{{ y }}">Resume:</label></th><td><textarea rows="10" cols="50" name="sop"  maxlength="500" required id="id_sop" value="{{ x }}"></textarea></td></tr>
                                    
                                   <tr>
                                      <td></td>
                                       <td><br><button type="submit" name="submit" value="Register" style="font-size: 1.5rem;font-family: Comic Sans MS, cursive, sans-serif" >MODIFY</button></td>
                                  </tr>

                               </table>
                           </form>
                       </div>
                   </div>
                   
         
         
               </div>
               
         
         
         {%endblock%}
          